apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
data:
  # credentials: BASE64ENCODED_OMNI_SERVICE_ACCOUNT
---
apiVersion: omni.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  endpoint: "<OMNI_ENDPOINT>"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
